#!/usr/bin/env node
const fs = require('fs');
const { compiler } = require('./');

const args = process.argv.slice(2);

const script = fs.readFileSync(`./${args[0]}.ki`, 'utf-8');
const compilation = compiler(script);

fs.writeFileSync(`./${args[0]}.js`, compilation);
